---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install golangci-lint"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "golangci-lint.yml"
