---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install gitlab-vars"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "gitlab-vars.yml"
