---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install ansible-summary"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "ansible-summary.yml"
