---
# https://taskfile.dev
version: '3'
tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  linter:
    desc: "execute linter"
    cmds:
      # - ansible-lint *.yml --skip-list name[template],meta-no-info,yaml[line-length],package-latest,latest[git]
      - ansible-lint .

  gen:
    desc: "generate doc/ci/molecule files"
    cmds:
      - ./gen-ci.sh
      - ./gen-docs.sh
      - ./gen-molecule-files.sh
