---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install pre-commit"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "pre-commit.yml"
