---

- name: Ensure unzip is installed.
  ansible.builtin.apt:
    name: ["unzip"]
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Ensure unzip is installed.
  ansible.builtin.package:
    name: ["unzip", "bzip2"]
    state: present
  # only for redhat distribution
  when: ansible_os_family == 'RedHat'

- name: Set github_token
  ansible.builtin.set_fact:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    cacheable: true
  changed_when: false
  check_mode: false

# include task from without_token.yml if no github_token
- name: Include task without_token.yml
  ansible.builtin.include_tasks: without_token.yml
  when: github_token == ""

- name: Include task with_token.yml
  ansible.builtin.include_tasks: with_token.yml
  when: github_token != ""
