---

- name: Sleep for 5 seconds
  ansible.builtin.wait_for:
    timeout: 5

# request the latest release from the github API without using a token
- name: Retrieve latest release information for github repository {{ gh_role_installer_repository }}
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ gh_role_installer_repository }}/releases/latest"
    timeout: 60
    headers:
      X-GitHub-Api-Version: "2022-11-28"
    return_content: true
  register: project_info
  changed_when: false
  check_mode: false
  when: github_token == ""

- name: Proceed to setup
  ansible.builtin.include_tasks: setup.yml
