---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install kube-linter"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "kube-linter.yml"
