---

gh_role_installer_version: "latest"
gh_role_installer_os: "linux"
gh_role_installer_arch: "amd64"
gh_role_installer_repository: "helmfile/helmfile"
gh_role_installer_release: "https://github.com/{{ gh_role_installer_repository }}/releases/download/v{{ version_to_install }}/helmfile_{{ version_to_install }}_{{ gh_role_installer_os }}_{{ gh_role_installer_arch }}.tar.gz"
gh_role_installer_release_is_archive: true
gh_role_installer_binary_name: "helmfile"
gh_role_installer_cmd_to_get_version: "helmfile version | grep Version | awk '{print $2}'"
gh_role_installer_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"
gh_role_install_directory: "/usr/local/bin"
