---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install helmchart-helper"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "helmchart-helper.yml"
