---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install git-town"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "git-town.yml"
