---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install restic-age-key"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "restic-age-key.yml"
