---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install eksctl"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "eksctl.yml"

    - name: "Install task"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "task.yml"

    - name: "Install k9s"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "k9s.yml"

    - name: "Install gum"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "gum.yml"

    - name: "Install jwt-cli"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        defaults_from: "jwt-cli.yml"

    - name: "Install act"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
      vars:
        gh_role_installer_version: "latest"
        gh_role_installer_os: "Linux"
        gh_role_installer_arch: "x86_64"
        gh_role_installer_repository: "nektos/act"
        gh_role_installer_release: "https://github.com/{{ gh_role_installer_repository }}/releases/download/v{{ version_to_install }}/act_{{ gh_role_installer_os }}_{{ gh_role_installer_arch }}.tar.gz"
        gh_role_installer_release_is_archive: true
        gh_role_installer_binary_name: "act"
        gh_role_installer_cmd_to_get_version: "act --version | awk '{ print $3 }'"
        gh_role_installer_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"

    - name: "Install zellij"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
      vars:
        gh_role_installer_version: "latest"
        gh_role_installer_os: "unknown-linux-musl"
        gh_role_installer_arch: "x86_64"
        gh_role_installer_repository: "zellij-org/zellij"
        gh_role_installer_release: "https://github.com/{{ gh_role_installer_repository }}/releases/download/v{{ version_to_install }}/zellij-{{ gh_role_installer_arch }}-{{ gh_role_installer_os }}.tar.gz"
        gh_role_installer_release_is_archive: true
        gh_role_installer_binary_name: "zellij"
        gh_role_installer_cmd_to_get_version: 'zellij --version | sed "s#zellij ##g"'
        gh_role_installer_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"
