---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        # dir: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/defaults/'
        file: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/defaults/jwt-cli.yml'
        # extensions:
        #   - 'yml'

    - name: Stat gh_role_installer
      ansible.builtin.stat:
        path: "/usr/bin/{{ gh_role_installer_binary_name }}"
      register: gh_role_installer_present
    - name: Check gh_role_installer is present
      ansible.builtin.assert:
        that:
          - gh_role_installer_present.stat.exists
        fail_msg: "gh_role_installer not setup"
        success_msg: "gh_role_installer is setup"
