---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install kubectl-ice"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "kubectl-ice.yml"
