---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install gitlab-issue-report"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "gitlab-issue-report.yml"
