---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Install opentofu"
      ansible.builtin.include_role:
        name: "sgaunet.gh_role_installer"
        vars_from: "opentofu.yml"
