---
name: CI-TEST-act
on:
  push:
    branches:
      - cicd/use-devbox

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2404
          - debian12
          - fedora41

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run Molecule tests.
        run: |
          # molecule destroy
          devbox run -- molecule test -s act
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
