---
name: CI-TEST-act
on:
  push:
    branches:
      - cicd/use-devbox

defaults:
  run:
    working-directory: 'sgaunet.gh-release-installer'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux9
          # - rockylinux8
          - ubuntu2204
          # - ubuntu2004
          - debian12
          # - debian11
          # - debian10
          - fedora39

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'sgaunet.gh-release-installer'

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          path: 'sgaunet.gh-release-installer'

      - name: Run Molecule tests.
        run: |
          # molecule destroy
          devbox run -- molecule test -s act
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
