---
name: CI
'on':
  pull_request:
  push:
    branches:
      - '*'

defaults:
  run:
    working-directory: 'sgaunet.gh-release-installer'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'sgaunet.gh-release-installer'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies.
        run: |
          pip3 install -r requirements.txt

      - name: Lint code.
        run: |
          ansible-lint

